general:
  database:
    # SQLITE, MYSQL
    type: "SQLITE"
    host: "localhost"
    # Port 3306 is MySQL's default. Port 27017 is MongoDB's default.
    port: 3306
    name: "superapix"
    username: "username"
    password: "password"
    # How often the data will be saved to file in mins. Default is 5 minutes.
    # This helps prevent issues if the server crashes.
    # Data is also saved at important points in the game.
    backup-period: 5
  # Default language for new players.")
  # This is the filename in the locale folder without .yml.")
  # If this does not exist, the default en-US will be used.")
  default-language: "en-US"
debug: true